# VideoClub con Seguridad

###
# @name keycloak get token (web angular react)
POST http://{{host}}:9091/realms/videoclub/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = videoclub-frontend &
username = usuarioadmin &
password = usuarioadmin &
grant_type = password &
scope = openid

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("access_token", response.body.access_token);
    });
%}

###
# @name keycloak get token (api)
POST http://{{host}}:9091/realms/videoclub/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = videoclub-backend &
client_secret = dstNSsANvqlaGfZCJa1mcYzP1EBAYP4N &
grant_type = client_credentials &
scope = openid test
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("access_token_api", response.body.access_token);
    });
%}

###
# @name api List get (with login and admin Role)
GET http://{{host}}:8080/movies
Authorization: Bearer {{access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name api List get (with login and admin Role)
GET http://{{host}}:9500/catalogo/movies
Authorization: Bearer {{access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


###
# @name actuator health
GET http://{{host}}:8080/metrics/health

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


###
# @name api docs
GET http://{{host}}:8080/api-docs

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name api List users (from Keycloak via declarative HTTP Interface)
GET http://{{host}}:8080/api/users
Authorization: Bearer {{access_token}}

###
# @name api Create user (in Keycloak via declarative HTTP Interface)
POST http://{{host}}:8080/api/users
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "carloslopez",
  "email": "carlos.lopez@gmail.com",
  "firstName": "Carlos",
  "lastName": "Lopez",
  "password": "Password123!",
  "group": "/videoclub-default/cliente"
}


