# VideoClub con Seguridad

@host = localhost
@keycloak_port = 9091
@backend_port = 8080
@gateway_port = 9500

@access_token = {{login.response.body.access_token}}
@access_token_api = {{login_api.response.body.access_token}}

# ====================================================================
# 1. Autenticación (Keycloak :9091)
# ====================================================================

###
# @name login
POST http://{{host}}:{{keycloak_port}}/realms/videoclub/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=videoclub-frontend&username=usuarioadmin&password=usuarioadmin&grant_type=password&scope=openid

###
# @name login_api
POST http://{{host}}:{{keycloak_port}}/realms/videoclub/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=videoclub-backend&client_secret=dstNSsANvqlaGfZCJa1mcYzP1EBAYP4N&grant_type=client_credentials&scope=openid


# ====================================================================
# 2. Backend Directo (:8080)
# ====================================================================

###
# @name backend_movies_list
GET http://{{host}}:{{backend_port}}/movies
Authorization: Bearer {{access_token}}

> {%
    client.test("Backend direct movies executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name backend_socios_list
GET http://{{host}}:{{backend_port}}/api/socios
Authorization: Bearer {{access_token}}

> {%
    client.test("Backend direct socios executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name backend_users_list
GET http://{{host}}:{{backend_port}}/api/users
Authorization: Bearer {{access_token}}

> {%
    client.test("Backend direct users executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name backend_user_create
POST http://{{host}}:{{backend_port}}/api/users
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "carloslopez",
  "email": "carlos.lopez@gmail.com",
  "firstName": "Carlos",
  "lastName": "Lopez",
  "password": "Password123!",
  "group": "/videoclub-default/cliente"
}


# ====================================================================
# 3. A través de API Gateway (:9500)
# ====================================================================

###
# @name gateway_movies_list
GET http://{{host}}:{{gateway_port}}/movies
Authorization: Bearer {{access_token}}

> {%
    client.test("Gateway movies executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name gateway_socios_list
GET http://{{host}}:{{gateway_port}}/api/socios
Authorization: Bearer {{access_token}}

> {%
    client.test("Gateway socios executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name gateway_users_list
GET http://{{host}}:{{gateway_port}}/api/users
Authorization: Bearer {{access_token}}

> {%
    client.test("Gateway users executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name gateway_user_create
POST http://{{host}}:{{gateway_port}}/api/users
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "carloslopez_gw",
  "email": "carlos.lopez.gw@gmail.com",
  "firstName": "CarlosGW",
  "lastName": "LopezGW",
  "password": "Password123!",
  "group": "/videoclub-default/cliente"
}


# ====================================================================
# 4. Observabilidad y Documentación (Backend :8080)
# ====================================================================

###
# @name actuator_health
GET http://{{host}}:{{backend_port}}/metrics/health

> {%
    client.test("Actuator health executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name api_docs
GET http://{{host}}:{{backend_port}}/api-docs

> {%
    client.test("Api docs executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



