services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: video-keycloak
    hostname: video-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - 9090:8080
    # json export tiene realm videoclub, client test-api y web, usuario, grupos y roles
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm
    healthcheck:
      test: [ "CMD", "curl", "--head","fsS", "http://localhost:8080/health/ready" ]
      interval: 5s
      timeout: 2s
      retries: 15
  postgres:
    image: postgres:16.3
    container_name: video-postgres
    hostname: video-postgres
    environment:
      - POSTGRES_DB=video
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
