spring:
  #Seguridad
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9090/realms/videoclub
          jwk-set-uri: http://localhost:9090/realms/videoclub/protocol/openid-connect/certs
  #Base de datos
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/video}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      TestNameUnique: TEST_NAME_UNIQUE
# swagger y keycloak integration
springdoc:
  oauth2:
    authorization-url: "http://localhost:9090/realms/videoclub/protocol/openid-connect/auth"
  api-docs:
    enabled: true
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    url: "/api-docs"
    oauth:
      client-id: web
      realm: videoclub

# Enable Actuator endpoints in application.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"