server:
  port: 9500

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: service-catalogo
              uri: http://host.docker.internal:8080
              predicates:
                - Path=/catalogo/**
              filters:
                - StripPrefix=1
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
            - id: service-notificaciones
              uri: http://host.docker.internal:8080
              predicates:
                - Path=/gateway/**
              filters:
                - StripPrefix=1
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
