name: videoclub
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: video-keycloak
    hostname: video-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
      KC_FEATURES: scripts
      KC_HEALTH_ENABLED: true
      KC_HTTP_MANAGEMENT_PORT: 9990
    ports:
      - 9090:8080
    # json export tiene realm videoclub, client test-api y web, usuario, grupos y roles
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9990;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 30s
      timeout: 10s
      retries: 3