name: videoclub
services:
  postgresql:
    image: postgres:16.3
    container_name: video-postgresql
    hostname: video-postgresql
    environment:
      - POSTGRES_DB=video
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 30s
      timeout: 10s
      retries: 5
