name: videoclub
services:
  pulsar:
    image: apachepulsar/pulsar:3.2.3
    ports:
      - 9080:8080
      - 6650:6650
    environment:
      PULSAR_MEM: ' -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g'
    command: bin/pulsar standalone
  # https://pulsar.apache.org/docs/3.3.x/administration-pulsar-manager/
  dashboard:
    image: apachepulsar/pulsar-manager:0.4.0
    ports:
      - "9527:9527"
      - "7750:7750"
    container_name: dashboard
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
      PULSAR_SERVICE_URL: pulsar://pulsar:6650
