server:
  port: 9500

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: service-catalogo
              uri: http://host.docker.internal:8080
              predicates:
                - Path=/movies/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            - id: service-socios
              uri: http://host.docker.internal:8080
              predicates:
                - Path=/api/socios/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            - id: service-users
              uri: http://host.docker.internal:8080
              predicates:
                - Path=/api/users/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            - id: service-notificaciones
              uri: http://host.docker.internal:8080
              predicates:
                - Path=/api/notifications/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            # Rutas con prefijo para compatibilidad retroactiva
            - id: legacy-catalogo
              uri: http://host.docker.internal:8080
              predicates:
                - Path=/catalogo/**
              filters:
                - StripPrefix=1
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            - id: legacy-gateway
              uri: http://host.docker.internal:8080
              predicates:
                - Path=/gateway/**
              filters:
                - StripPrefix=1
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
