apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '(?:\b(?:trace_id|traceId|traceID)[:=]\s*"?|\[[^,]+,)([a-f0-9]{16,32})'
          name: TraceID
          url: '$${__value.raw}'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags: ['service', 'container']
        filterByTrace: true
        filterBySpan: false
      tracesToMetrics:
        datasourceUid: 'prometheus'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'
